install CLEAN="false":
    go mod {{ if CLEAN == "true" { "download" } else { "tidy" } }}

[group('check')]
test:
    go test ./main/...

[group('check')]
cov:
    go test -coverprofile=coverage.out ./main/...

format:
    just --fmt
    go fmt ./...

generate-website:
    cd website/ && hugo --minify
